---
- name: Test SSH connectivity to instances
  hosts: all
  vars:
    ansible_ssh_private_key_file: /root/.ssh/alpaca.pem
  tasks:
    - name: Test connectivity to instances
      ping:

    - name: Show ping results
      debug:
        msg: "Ping successful to {{ inventory_hostname }}"
